name: Build & Deploy Windows (C)

on:
  push:
    branches:
      - sivadev

jobs:
  build:
    name: Build C Project on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-make

      - name: Build using windows.bat
        shell: cmd
        run: |
          windows.bat
